/* Bocali 0.3: map, merchant zones and address checkout. No real orders or charges. */
'use strict';
const D=window.PedeDelivery;
const geo={zoom:13,center:{lng:-45.461,lat:-22.925},tiles:false,selected:null,edit:null,owner:null,selection:null,confirmed:null,results:[],sequence:0,ready:false};
const zoneColors=['#368777','#dc9341','#8d7fab','#cb5752'];
D.migrate(state);
function mercator(p,z){const n=256*2**z,s=Math.sin(p.lat*Math.PI/180);return {x:(p.lng+180)/360*n,y:(.5-Math.log((1+s)/(1-s))/(4*Math.PI))*n};}
function unmercator(x,y,z){const n=256*2**z;return {lng:x/n*360-180,lat:Math.atan(Math.sinh(Math.PI*(1-2*y/n)))*180/Math.PI};}
function screenPoint(p){const c=mercator(geo.center,geo.zoom),v=mercator(p,geo.zoom);return [v.x-c.x+400,v.y-c.y+260];}
function mapSVG(id){
 const shop=id==='checkout-map'?findShop(state.cart.storeId):adminShop(),cfg=shop.deliveryConfig;
 const c=mercator(geo.center,geo.zoom),left=c.x-400,top=c.y-260;let background='';
 if(geo.tiles&&/^https?:$/.test(location.protocol)){
  const n=2**geo.zoom;for(let x=Math.floor(left/256);x<=Math.floor((left+800)/256);x++){for(let y=Math.floor(top/256);y<=Math.floor((top+520)/256);y++){if(x<0||y<0||x>=n||y>=n)continue;background+=`<image href="https://tile.openstreetmap.org/${geo.zoom}/${x}/${y}.png" x="${x*256-left}" y="${y*256-top}" width="256" height="256"/>`;}}
 }else{
  background='<defs><pattern id="geo-grid-'+id+'" width="50" height="50" patternUnits="userSpaceOnUse"><path d="M50 0H0V50" fill="none" stroke="#d8dfd3" stroke-width="1"/></pattern></defs><rect width="800" height="520" fill="#f0f2e9"/><rect width="800" height="520" fill="url(#geo-grid-'+id+')"/>';
  for(let i=100;i<800;i+=200){const p=unmercator(left+i,top,geo.zoom);background+=`<text x="${i}" y="505" fill="#839182" font-size="11" text-anchor="middle">${p.lng.toFixed(3)}\u00b0</text>`;}
  background+='<text x="400" y="40" text-anchor="middle" fill="#6c7c6b" font-size="13" letter-spacing="2">\u00c1REAS FICT\u00cdCIAS \u00b7 SEM MALHA DE RUAS</text>';
 }
 const zones=[...cfg.zones].filter(z=>z.active).sort((a,b)=>a.priority-b.priority),layers=[];
 for(const z of zones){const color=z.kind==='blocked'?'#cb5752':zoneColors[cfg.zones.indexOf(z)%3];layers.push(`<polygon points="${z.ring.map(p=>screenPoint({lng:p[0],lat:p[1]}).join(',')).join(' ')}" fill="${color}" fill-opacity="${geo.tiles?.19:.13}" stroke="${color}" stroke-width="2.3"/>`);}
 for(const z of zones){const p=z.ring[Math.min(1,z.ring.length-1)],xy=screenPoint({lng:p[0],lat:p[1]}),color=z.kind==='blocked'?'#cb5752':zoneColors[cfg.zones.indexOf(z)%3];layers.push(`<g transform="translate(${xy[0]},${xy[1]+22})"><rect x="-39" y="-14" width="78" height="26" rx="10" fill="white" stroke="${color}"/><text text-anchor="middle" y="4" font-weight="700" font-size="12" fill="${color}">${z.kind==='blocked'?'SEM ENTREGA':esc(brl(z.fee))}</text></g>`);}
 if(geo.edit&&id==='admin-map'){const pts=geo.edit.ring.map(p=>screenPoint({lng:p[0],lat:p[1]}));layers.push(`<polyline points="${pts.map(p=>p.join(',')).join(' ')}" fill="#ed875422" stroke="#d76537" stroke-width="3" stroke-dasharray="7 4"/>`);pts.forEach((p,i)=>layers.push(`<circle cx="${p[0]}" cy="${p[1]}" r="6" fill="#d76537" stroke="white" stroke-width="2"/><text x="${p[0]+10}" y="${p[1]-9}" font-size="12" font-weight="700">${i+1}</text>`));}
 const selection=id==='checkout-map'?geo.selection?.point:geo.selected;
 if(selection){const p=screenPoint(selection);layers.push(`<g transform="translate(${p[0]},${p[1]})"><circle r="17" fill="#173f361b"/><path d="M0 0C-4-7-13-16-13-24a13 13 0 0 1 26 0C13-16 4-7 0 0" fill="#173f36" stroke="white" stroke-width="2.5"/><circle cy="-24" r="4" fill="white"/></g>`);}
 return `<svg class="geo-svg map-focus" id="${id}-svg" data-geo-map="${id}" viewBox="0 0 800 520" role="img" aria-label="Mapa de \u00e1reas de entrega da loja. Use os exemplos abaixo para testar sem clicar no mapa." tabindex="0">${background}${layers.join('')}</svg>`;
}
function mapBox(id){return `<div class="zone-map" id="${id}">${mapSVG(id)}<div class="map-attribution">${geo.tiles?'Dados e mapas: <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">\u00a9 OpenStreetMap</a>':'Esquema de teste \u00b7 n\u00e3o representa limites oficiais'}</div></div><div class="map-bar"><button type="button" class="btn secondary" data-geo="zoom-in" aria-label="Aproximar mapa">+</button><button type="button" class="btn secondary" data-geo="zoom-out" aria-label="Afastar mapa">\u2212</button><button type="button" class="btn secondary" data-geo="center">Centralizar</button><button type="button" class="btn secondary" data-geo="tiles">${geo.tiles?'Desligar ruas online':'Carregar ruas online'}</button></div>`;}
function refreshMap(){['admin-map','checkout-map'].forEach(id=>{const el=document.getElementById(id);if(el)el.innerHTML=mapSVG(id)+`<div class="map-attribution">${geo.tiles?'Dados e mapas: <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">\u00a9 OpenStreetMap</a>':'Esquema de teste \u00b7 sem ruas e sem limites oficiais'}</div>`;});}
function feeResult(q){return q.ok?`<div class="quote-result"><div class="eyebrow">TAXA ENCONTRADA</div><strong class="quote-price">${brl(q.fee)}</strong><p>${esc(q.zoneName)}${q.overlap?'<br>Sobreposi\u00e7\u00e3o: prioridade '+q.priority+' aplicada.':''}</p></div>`:`<div class="quote-result error"><strong>${q.code==='outside'?'Fora da cobertura':'Entrega n\u00e3o liberada'}</strong><p>${esc(q.message)}</p></div>`;}
function deliveryView(){
 const s=adminShop();if(geo.owner!==s.id){geo.owner=s.id;geo.edit=null;geo.selected=null;geo.center={...s.deliveryConfig.reference};geo.zoom=13;}
 const cfg=s.deliveryConfig,active=cfg.zones.filter(z=>z.active&&z.kind==='delivery');
 return `${adminHeading('\u00c1reas e taxas de entrega.','Cada loja desenha a cobertura. O endere\u00e7o determina a taxa.')}<div class="notice">Demonstra\u00e7\u00e3o: contornos e valores fict\u00edcios. N\u00e3o s\u00e3o os bairros oficiais nem as taxas do Cantinho. A refer\u00eancia no mapa n\u00e3o \u00e9 a localiza\u00e7\u00e3o da loja.</div><div class="delivery-grid"><section class="map-panel"><div class="map-panel-head"><div><h2>${esc(cfg.city)} \u00b7 ${esc(cfg.state)}</h2><p class="map-caption">${active.length} \u00e1reas ativas \u00b7 configura\u00e7\u00e3o exclusiva de ${esc(s.name)}</p></div><span class="map-mode">${geo.tiles?'RUAS ONLINE':'MODO ESQUEM\u00c1TICO'}</span></div>${mapBox('admin-map')}<div class="map-footer">${geo.edit?'Clique no mapa para acrescentar pontos ao contorno. Use Salvar quando terminar.':'Clique em um ponto para simular a taxa. Para criar um contorno, toque em Nova \u00e1rea.'}<p class="zone-help-line">Ruas online s\u00e3o opcionais, exigem internet e o servidor local. O provedor recebe IP e regi\u00e3o visualizada. Nenhum GPS \u00e9 solicitado.</p></div></section><aside class="zones-side">${geo.edit?zoneEditorHTML():zoneListHTML(s)}<section class="panel"><div class="eyebrow muted">SIMULADOR DE COBERTURA</div><h2 style="margin-top:7px">Quanto custa entregar?</h2><p class="small muted" style="margin-top:9px">Experimente pontos fict\u00edcios dentro e fora das \u00e1reas.</p><div class="sample-buttons">${[0,1,2,3].map(i=>`<button class="btn secondary" data-geo="sample" data-index="${i}">${i===3?'Fora da \u00e1rea':'Ponto '+String.fromCharCode(65+i)}</button>`).join('')}</div><div id="admin-quote">${geo.selected?feeResult(D.quote(s,geo.selected)):'<div class="geo-status muted">Selecione um ponto de teste para ver a taxa.</div>'}</div><a class="btn full spaced" href="#/loja/${esc(s.id)}">Testar no pedido ${ico('arrow')}</a></section><div class="zone-note"><strong>Regra de encontro das \u00e1reas</strong><br>Vale a maior prioridade, sem somar taxas. Empate bloqueia o pedido at\u00e9 corre\u00e7\u00e3o. Uma \u00e1rea sem entrega sempre bloqueia. Retirada no balc\u00e3o tem taxa zero.</div></aside></div>`;
}
function zoneListHTML(s){return `<section class="panel"><div class="row" style="justify-content:space-between"><h2>Suas \u00e1reas</h2><button class="btn secondary" data-geo="new">+ Nova \u00e1rea</button></div><div class="zone-list">${s.deliveryConfig.zones.map((z,i)=>`<div class="zone-row ${z.active?'':'disabled'}"><span class="zone-dot" style="background:${z.kind==='blocked'?'#cb5752':zoneColors[i%3]}"></span><div><strong>${esc(z.name)}</strong><small>${z.kind==='blocked'?'Sem entrega':'Prioridade '+z.priority} \u00b7 ${z.active?'ativa':'pausada'}</small></div><div style="text-align:right"><strong class="zone-price">${z.kind==='blocked'?'\u2014':brl(z.fee)}</strong><button class="text-link" data-geo="edit" data-id="${esc(z.id)}">Editar</button></div></div>`).join('')}</div><p class="zone-rules">Os pre\u00e7os s\u00e3o apenas exemplos.<br><strong>A regra \u00e9 por \u00e1rea, n\u00e3o por quil\u00f4metro.</strong></p></section>`;}
function zoneEditorHTML(){const z=geo.edit;return `<section class="panel"><div class="zone-edit-title"><h2>Editar contorno</h2><button class="text-link" data-geo="cancel-edit">Cancelar</button></div><form id="zone-form"><label class="field"><span>Nome da \u00e1rea</span><input id="zone-name" maxlength="60" required value="${esc(z.name)}"></label><div class="field-grid"><label class="field"><span>Taxa (R$)</span><input id="zone-fee" inputmode="decimal" value="${(z.fee/100).toFixed(2).replace('.',',')}" required></label><label class="field"><span>Prioridade</span><input id="zone-priority" type="number" min="0" max="999" step="1" value="${z.priority}" required></label></div><label class="field"><span>Tipo</span><select id="zone-kind"><option value="delivery" ${z.kind==='delivery'?'selected':''}>Entrega dispon\u00edvel</option><option value="blocked" ${z.kind==='blocked'?'selected':''}>Sem entrega / exclus\u00e3o</option></select></label><label class="check-label"><input id="zone-active" type="checkbox" ${z.active?'checked':''}>\u00c1rea ativa</label><div class="zone-point-count" id="zone-point-count">${z.ring.length} pontos no contorno</div><div class="sample-buttons"><button type="button" class="btn secondary" data-geo="undo-point">Desfazer ponto</button><button type="button" class="btn secondary" data-geo="redraw">Redesenhar</button></div><details class="spaced"><summary class="small">Adicionar ponto pelas coordenadas</summary><div class="field-grid spaced"><label class="field"><span>Latitude</span><input id="vertex-lat" type="number" step="any" placeholder="-22.925"></label><label class="field"><span>Longitude</span><input id="vertex-lng" type="number" step="any" placeholder="-45.461"></label></div><button type="button" class="btn secondary" data-geo="add-vertex">Adicionar ponto</button></details><button type="submit" class="btn full spaced">Salvar \u00e1rea no teste</button><p class="zone-help-line">A mudan\u00e7a vale para novos c\u00e1lculos. Pedidos j\u00e1 criados mant\u00eam o valor original.</p></form></section>`;}
function mountDeliveryMap(){refreshMap();}
function keepEditFields(){if(!geo.edit||!$('#zone-form'))return;geo.edit.name=$('#zone-name').value;const s=$('#zone-fee').value.trim();geo.edit.fee=/^0([,.]0{1,2})?$/.test(s)?0:C.moneyToCents(s);geo.edit.priority=Number($('#zone-priority').value);geo.edit.kind=$('#zone-kind').value;geo.edit.active=$('#zone-active').checked;}
function updatePointCount(){if($('#zone-point-count'))$('#zone-point-count').textContent=geo.edit.ring.length+' pontos no contorno';refreshMap();}
function addressFormHTML(){return `<div class="delivery-fields spaced"><label class="field"><span>Rua / avenida</span><input id="addr-street" maxlength="120" placeholder="Use um exemplo abaixo" autocomplete="off"></label><label class="field"><span>N\u00famero</span><input id="addr-number" maxlength="20" placeholder="100" autocomplete="off"></label><label class="field"><span>Bairro</span><input id="addr-neighborhood" maxlength="120" autocomplete="off"></label><label class="field"><span>CEP (opcional)</span><input id="addr-postcode" maxlength="9" inputmode="numeric" autocomplete="off"></label><label class="field"><span>Cidade</span><input id="addr-city" value="Pindamonhangaba" maxlength="120" autocomplete="off"></label><label class="field"><span>UF</span><input id="addr-state" value="SP" maxlength="2" autocomplete="off"></label><label class="field wide"><span>Complemento (opcional)</span><input id="addr-complement" maxlength="120" autocomplete="off"></label></div><div class="sample-buttons"><button type="button" class="btn" data-geo="lookup">Localizar endere\u00e7o</button>${[0,1,2,3].map(i=>`<button type="button" class="btn secondary" data-geo="checkout-sample" data-index="${i}">${i===3?'Fora da \u00e1rea':'Exemplo '+String.fromCharCode(65+i)}</button>`).join('')}</div><div id="geo-status" class="geo-status" role="status">Use os exemplos fict\u00edcios. A busca real s\u00f3 funciona com o servidor e o provedor configurados.</div><div id="address-results"></div><div class="checkout-map">${mapBox('checkout-map')}</div><div id="delivery-quote"></div><button type="button" class="btn soft full spaced" data-geo="confirm-address" id="confirm-address" disabled>Confirmar este endere\u00e7o e esta taxa</button>`;}
function readAddress(){const a={};['street','number','neighborhood','city','state','postcode','complement'].forEach(k=>a[k]=$('#addr-'+k)?.value.trim()||'');a.state=a.state.toUpperCase();const digits=a.postcode.replace(/\D/g,'');a.postcode=digits.length===8?digits.slice(0,5)+'-'+digits.slice(5):'';return a;}
function fillAddress(a){Object.entries(a).forEach(([k,v])=>{const e=$('#addr-'+k);if(e)e.value=v;});}
function checkout(){try{C.validateCart(state);}catch(e){return toast(e.message);}checkoutMode='delivery';checkoutPayment='cash';geo.selection=null;geo.confirmed=null;geo.results=[];geo.sequence++;geo.center={...findShop(state.cart.storeId).deliveryConfig.reference};geo.zoom=13;openModal('Endere\u00e7o e taxa de entrega',`<div class="notice">Confira o endereço, a forma de recebimento e o pagamento antes de enviar.</div><h3 class="small spaced" style="margin-bottom:12px">Como voc\u00ea receberia?</h3><label class="checkout-option"><input type="radio" name="fulfillment" value="delivery" checked>Entrega<span class="option-detail">Por endere\u00e7o</span></label><label class="checkout-option"><input type="radio" name="fulfillment" value="pickup">Retirada no balc\u00e3o<span class="option-detail">Sem taxa</span></label><div id="delivery-example">${addressFormHTML()}</div><h3 class="small spaced" style="margin-bottom:12px">Pagamento</h3><label class="checkout-option"><input type="radio" name="payment" value="cash" checked>Dinheiro</label><label class="checkout-option"><input type="radio" name="payment" value="card">Cart\u00e3o na entrega / retirada</label><label class="checkout-option"><input type="radio" name="payment" value="pix">Pix (n\u00e3o integrado)</label><label class="field spaced"><span>Observa\u00e7\u00e3o do pedido (opcional)</span><textarea id="checkout-note" maxlength="200" placeholder="Ex.: sem cebola, molho separado."></textarea></label><div id="checkout-totals"></div><button class="btn full spaced" id="place-order" data-action="place-order" disabled>Continuar para conferir</button><p class="cart-caption">O servidor recalcula produtos, adicionais, taxa e total antes de criar o pedido.</p>`);$('#modal').classList.add('delivery-modal');updateDeliveryCheckout();checkGeoServer();}
function checkoutTotals(){const t=C.totals(state.cart,checkoutMode==='pickup'?0:geo.confirmed?.quote?.fee||0);const known=checkoutMode==='pickup'||!!geo.confirmed;return `<div class="amount-row"><span>Produtos</span><span>${brl(t.subtotal)}</span></div><div class="amount-row"><span>Taxa de entrega</span><span>${known?brl(t.fee):'A calcular'}</span></div><div class="amount-row total"><span>Total</span><span>${known?brl(t.total):'A confirmar'}</span></div>`;}
function updateDeliveryCheckout(){if(!$('#checkout-totals'))return;const shop=findShop(state.cart.storeId);let q=geo.selection?D.quote(shop,geo.selection.point):null;if(geo.confirmed){try{D.validateDelivery(shop,geo.confirmed);}catch{geo.confirmed=null;}}
 $('#checkout-totals').innerHTML=checkoutTotals();$('#place-order').disabled=checkoutMode==='delivery'&&!geo.confirmed;
 const confirm=$('#confirm-address');if(confirm){confirm.disabled=!q?.ok||!geo.selection?.precise||!D.validAddress(readAddress());confirm.textContent=geo.confirmed?'Endere\u00e7o e taxa confirmados':'Confirmar este endere\u00e7o e esta taxa';}
 if($('#delivery-quote'))$('#delivery-quote').innerHTML=q?feeResult(q):'';refreshMap();}
function selectAddress(selection){geo.selection=D.clone(selection);geo.confirmed=null;geo.sequence++;fillAddress(selection.address);$('#address-results').innerHTML='';$('#geo-status').textContent=selection.source==='demo'?'Ponto fict\u00edcio localizado no teste. Confira o mapa e confirme a taxa.':selection.precise?'Resultado localizado. Confira o endere\u00e7o retornado e confirme o ponto.':'Resultado impreciso: rua, bairro ou cidade n\u00e3o bastam. Corrija o n\u00famero/endereco e consulte novamente.';updateDeliveryCheckout();}
async function checkGeoServer(){geo.ready=false;if(location.protocol==='file:')return;try{const r=await fetch('/api/health',{signal:AbortSignal.timeout(2500)});const d=await r.json();geo.ready=!!d.geocoding;}catch{} }
async function lookupAddress(){const address=readAddress();geo.sequence++;const seq=geo.sequence;geo.confirmed=null;geo.selection=null;geo.results=[];$('#address-results').innerHTML='';updateDeliveryCheckout();if(!D.validAddress(address)){return $('#geo-status').textContent='Preencha rua, n\u00famero, bairro, cidade e UF. Confira o CEP, se informado.';}
 for(let i=0;i<4;i++){const s=D.sample(i);if(D.addressKey({...address,complement:''})===D.addressKey(s.address)){s.address=address;selectAddress(s);return;}}
 if(!geo.ready){$('#geo-status').textContent='Busca real n\u00e3o conectada. Execute o servidor e configure GEOAPIFY_API_KEY. Nenhum ponto nem taxa foi inventado.';return;}
 if(!confirm('Consultar este endere\u00e7o no provedor Geoapify? Rua, n\u00famero, bairro, cidade, UF e CEP ser\u00e3o enviados. O complemento n\u00e3o ser\u00e1 enviado. Use somente dados fict\u00edcios neste prot\u00f3tipo.'))return;
 $('#geo-status').textContent='Consultando o endere\u00e7o...';try{const safe={...address};delete safe.complement;const r=await fetch('/api/geocode',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address:safe}),signal:AbortSignal.timeout(14000)});const data=await r.json();if(seq!==geo.sequence||!$('#addr-street')||D.addressKey(readAddress())!==D.addressKey(address))return;if(!r.ok)throw new Error(data.error||'Falha ao consultar o endere\u00e7o.');geo.results=(data.results||[]).map(x=>({...x,address:{...x.address,complement:address.complement}}));$('#geo-status').textContent=geo.results.length?'Selecione o resultado correto. O valor s\u00f3 ser\u00e1 liberado ap\u00f3s conferir o ponto.':'Endere\u00e7o n\u00e3o localizado. Corrija e tente novamente.';$('#address-results').innerHTML=geo.results.length?`<div class="address-result"><strong>Resultados encontrados</strong>${geo.results.map((x,i)=>`<button type="button" class="btn secondary" data-geo="choose-result" data-index="${i}">${esc(x.formatted||D.formatAddress(x.address))}${x.precise?'':' \u2014 impreciso'}</button>`).join('')}<p class="zone-help-line">Geocodifica\u00e7\u00e3o: Geoapify \u00b7 dados OpenStreetMap</p></div>`:'';}catch(e){if(seq===geo.sequence&&$('#geo-status'))$('#geo-status').textContent='N\u00e3o foi poss\u00edvel localizar. Nenhuma taxa foi aplicada. '+(e.name==='TimeoutError'?'Tempo de consulta excedido.':e.message);}}
function placeOrder(){const b=$('#place-order');if(b)b.disabled=true;try{if(checkoutMode==='delivery'&&(!geo.confirmed||D.addressKey(readAddress())!==geo.confirmed.addressKey))throw new Error('O endere\u00e7o mudou. Localize e confirme novamente.');const o=C.createOrder(state,{fulfillment:checkoutMode,payment:checkoutPayment,note:$('#checkout-note').value,delivery:checkoutMode==='delivery'?geo.confirmed:null});save();render();openModal('Pedido criado',`<div class="success"><div class="success-mark">${ico('check')}</div><h2>${esc(o.id)}</h2><p>${esc(o.storeName)}<br>Entrega: <strong>${brl(o.fee)}</strong><br>Total: <strong>${brl(o.total)}</strong></p>${o.delivery?`<div class="delivery-order"><strong>${esc(o.delivery.quote.zoneName)}</strong>${esc(D.formatAddress(o.delivery.address))}</div>`:'<p>Retirada no balc\u00e3o, sem taxa de entrega.</p>'}<button class="btn full" data-action="goto-orders">Acompanhar pedido</button><button class="btn secondary full" data-action="goto-admin" data-store="${esc(o.storeId)}">Ver no aceitador da loja</button></div>`);}catch(e){toast(e.message);geo.confirmed=null;updateDeliveryCheckout();}}
function deliveryOrderHTML(o){return o.delivery?`<div class="delivery-order"><strong>${esc(D.formatAddress(o.delivery.address))}</strong>${esc(o.delivery.quote.zoneName)} \u00b7 Taxa registrada: ${brl(o.fee)}<br><small>Endere\u00e7o de teste. N\u00e3o despachar.</small></div>`:'';}
function deliveryReceiptHTML(o){return o.delivery?`<p><b>Endere\u00e7o de teste:</b><br>${esc(D.formatAddress(o.delivery.address))}<br>${esc(o.delivery.quote.zoneName)} \u00b7 Taxa: ${brl(o.fee)}<br>N\u00e3o despachar.</p>`:'<p>Endere\u00e7o de teste n\u00e3o registrado. N\u00e3o despachar.</p>';}
function deliverySummaryHTML(s){const rates=s.deliveryConfig.zones.filter(z=>z.active&&z.kind==='delivery').map(z=>z.fee);return `<div class="delivery-strip"><div><strong>Entrega por \u00e1rea</strong><p>${rates.length?'Taxas de exemplo a partir de '+brl(Math.min(...rates))+'.':'Nenhuma \u00e1rea de entrega ativa.'} Cada endere\u00e7o precisa estar na cobertura.</p></div><a class="btn secondary" href="#/areas">Configurar mapa e taxas</a></div>`;}
document.addEventListener('click',e=>{
 const target=e.target.closest('[data-geo]');if(target){const action=target.dataset.geo,index=Number(target.dataset.index);e.preventDefault();
 if(action==='zoom-in'||action==='zoom-out'){geo.zoom=Math.max(10,Math.min(18,geo.zoom+(action==='zoom-in'?1:-1)));refreshMap();}
 else if(action==='center'){geo.center={...(state.cart.storeId&&$('#checkout-map')?findShop(state.cart.storeId):adminShop()).deliveryConfig.reference};geo.zoom=13;refreshMap();}
 else if(action==='tiles'){if(location.protocol==='file:')return toast('Para carregar ruas online, abra o projeto pelo servidor local. O HTML avulso mant\u00e9m o mapa esquem\u00e1tico.');if(!geo.tiles&&!confirm('Carregar mapas OpenStreetMap pela internet? O provedor recebe IP e regi\u00e3o visualizada. Use apenas teste moderado; n\u00e3o h\u00e1 garantia de disponibilidade.'))return;geo.tiles=!geo.tiles;target.textContent=geo.tiles?'Desligar ruas online':'Carregar ruas online';refreshMap();}
 else if(action==='sample'){geo.selected=D.sample(index).point;$('#admin-quote').innerHTML=feeResult(D.quote(adminShop(),geo.selected));refreshMap();}
 else if(action==='new'){geo.edit={id:C.uid(),storeId:adminShop().id,name:'Nova \u00e1rea',fee:500,priority:40,kind:'delivery',active:true,ring:[]};render();}
 else if(action==='edit'){geo.edit=D.clone(adminShop().deliveryConfig.zones.find(z=>z.id===target.dataset.id));render();}
 else if(action==='cancel-edit'){geo.edit=null;render();}
 else if(action==='undo-point'){keepEditFields();geo.edit.ring.pop();updatePointCount();}
 else if(action==='redraw'){keepEditFields();geo.edit.ring=[];updatePointCount();}
 else if(action==='add-vertex'){const lat=$('#vertex-lat').value,lng=$('#vertex-lng').value;const p={lat:Number(lat),lng:Number(lng)};if(!lat||!lng||!D.validPoint(p))return toast('Informe latitude e longitude v\u00e1lidas.');keepEditFields();geo.edit.ring.push([p.lng,p.lat]);updatePointCount();}
 else if(action==='checkout-sample'){selectAddress(D.sample(index));}
 else if(action==='lookup')lookupAddress();
 else if(action==='choose-result'){const s=geo.results[index];if(s)selectAddress(s);}
 else if(action==='confirm-address'){try{geo.selection.address=readAddress();geo.confirmed=D.confirmSelection(findShop(state.cart.storeId),geo.selection);$('#geo-status').textContent='Endere\u00e7o e taxa confirmados. Confira o total antes de simular o pedido.';updateDeliveryCheckout();}catch(err){toast(err.message);}}
 return;}
 const map=e.target.closest('[data-geo-map]');if(!map)return;const xy=new DOMPoint(e.clientX,e.clientY).matrixTransform(map.getScreenCTM().inverse()),c=mercator(geo.center,geo.zoom),p=unmercator(c.x+xy.x-400,c.y+xy.y-260,geo.zoom);
 if(map.dataset.geoMap==='admin-map'){if(geo.edit){keepEditFields();if(geo.edit.ring.length>=100)return toast('Limite de 100 pontos por \u00e1rea.');geo.edit.ring.push([p.lng,p.lat]);updatePointCount();}else{geo.selected=p;$('#admin-quote').innerHTML=feeResult(D.quote(adminShop(),p));refreshMap();}}
 else toast('O ponto do cliente vem do endere\u00e7o localizado. Corrija o endere\u00e7o ou use outro exemplo; n\u00e3o escolha uma taxa clicando no mapa.');
});
document.addEventListener('input',e=>{if(!e.target.id.startsWith('addr-'))return;geo.confirmed=null;geo.selection=null;geo.sequence++;geo.results=[];if($('#address-results'))$('#address-results').innerHTML='';if($('#geo-status'))$('#geo-status').textContent='Endere\u00e7o alterado. Localize e confirme novamente.';updateDeliveryCheckout();});
document.addEventListener('change',e=>{if(e.target.name==='fulfillment')updateDeliveryCheckout();});
document.addEventListener('submit',e=>{if(e.target.id!=='zone-form')return;e.preventDefault();try{keepEditFields();D.saveZone(adminShop(),geo.edit);save();geo.edit=null;render();toast('\u00c1rea salva. Novos pedidos usar\u00e3o a nova configura\u00e7\u00e3o.');}catch(err){toast(err.message);}});
window.addEventListener('storage',e=>{if(e.key===KEY&&$('#checkout-totals')){D.migrate(state);geo.confirmed=null;updateDeliveryCheckout();if($('#geo-status'))$('#geo-status').textContent='Os dados mudaram em outra aba. Confira o endere\u00e7o e a taxa novamente.';}});
$('#modal').addEventListener('close',()=>{geo.sequence++;$('#modal').classList.remove('delivery-modal');});
if(!location.hash)location.hash='#/areas';else render();save();
